import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { Header } from './Header'

const jetBrainMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${jetBrainMono.variable} antialiased`}>
        <main className=' bg-zinc-900'>
          <Header />
          <div className='w-6xl mx-auto'>{children}</div>
          <footer>footer here</footer>
        </main>
      </body>
    </html>
  )
}
